spring:
  application:
    name: BARBERSHOP-SERVICE
  datasource:
    url: jdbc:postgresql://barbershop_service_postgres:5432/barbershop_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-request-size: 50MB
      max-file-size: 50MB
  config:
    import: optional:file:../.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate



cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ru-central1
    endpoint:
      s3:
        static: https://storage.yandexcloud.net
    bucket:
      name: barbershop-app

server:
  port: 8081
