spring:
  application:
    name: ${barbershop.service.name}
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/barbershop_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-request-size: 50MB
      max-file-size: 50MB
  config:
    import: optional:file:../.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.service.host}:${eureka.service.port}/eureka


cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ru-central1
    endpoint:
      s3:
        static: https://storage.yandexcloud.net
    bucket:
      name: barbershop-app

server:
  port: ${barbershop.service.port}
